INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','StaffSchool','StaffEmail',1,'varchar','150','1','1','1','SpedStaffMember','StaffEmail','0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','StaffSchool','SchoolCode',2,'varchar','10','1','1','1','School','SchoolCode','0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','SelectLists','Type',1,'varchar','20','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','SelectLists','SubType',2,'varchar','20','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','SelectLists','EnrichID',3,'varchar','150','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','SelectLists','StateCode',4,'varchar','10','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','SelectLists','LegacySpedCode',5,'varchar','150','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','SelectLists','EnrichLabel',6,'varchar','254','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','District','DistrictCode',1,'varchar','10','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','District','DistrictName',2,'varchar','254','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','School','SchoolCode',1,'varchar','10','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','School','SchoolName',2,'varchar','254','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','School','DistrictCode',3,'varchar','10','1','1','1','District','DistrictCode','0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','School','MinutesPerWeek',4,'int','4','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','StudentRefID',1,'varchar','150','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','StudentLocalID',2,'varchar','50','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','StudentStateID',3,'varchar','50','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','Firstname',4,'varchar','50','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','MiddleName',5,'varchar','50','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','LastName',6,'varchar','50','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','Birthdate',7,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','Gender',8,'varchar','150','1','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Gender','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','MedicaidNumber',9,'varchar','50','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','GradeLevelCode',10,'varchar','150','1','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Grade','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','ServiceDistrictCode',11,'varchar','10','1','0','0',NULL,NULL,'1','District','Districtcode',NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','ServiceSchoolCode',12,'varchar','10','1','0','0',NULL,NULL,'1','School','Schoolcode ',NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','HomeDistrictCode',13,'varchar','10','1','0','0',NULL,NULL,'1','District','Districtcode',NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','HomeSchoolCode',14,'varchar','10','1','0','0',NULL,NULL,'1','School','Schoolcode ',NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','IsHispanic',15,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','IsAmericanIndian',16,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','IsAsian',17,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','IsBlackAfricanAmerican',18,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','IsHawaiianPacIslander',19,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','IsWhite',20,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','Disability1Code',21,'varchar','150','1','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','Disability2Code',22,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','Disability3Code',23,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','Disability4Code',24,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','Disability5Code',25,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','Disability6Code',26,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','Disability7Code',27,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','Disability8Code',28,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','Disability9Code',29,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','EsyElig',30,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','EsyTBDDate',31,'datetime','10','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','ExitDate',32,'datetime','10','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','ExitCode',33,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Exit','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Student','SpecialEdStatus',34,'char','1','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''A'',''E''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','IepRefID',1,'varchar','150','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','StudentRefID',2,'varchar','150','1','1','1','Student','StudentRefID','0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','IEPMeetDate',3,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','IEPStartDate',4,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','IEPEndDate',5,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','NextReviewDate',6,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','InitialEvaluationDate',7,'datetime','10','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','LatestEvaluationDate',8,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','NextEvaluationDate',9,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','EligibilityDate',10,'datetime','10','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','ConsentForServicesDate',11,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','ConsentForEvaluationDate',12,'datetime','10','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','LREAgeGroup',13,'varchar','3','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','LRECode',14,'varchar','150','1','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','LRE','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','MinutesPerWeek',15,'int','4','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','IEP','ServiceDeliveryStatement',16,'varchar','8000','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','SpedStaffMember','StaffEmail',1,'varchar','150','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','SpedStaffMember','Firstname',2,'varchar','50','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','SpedStaffMember','Lastname',3,'varchar','50','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','SpedStaffMember','EnrichRole',4,'varchar','50','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','ServiceType',1,'varchar','10','1','0','0',NULL,NULL,'1','SelectLists','SubType','Service','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','ServiceRefId',2,'varchar','150','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','IepRefId',3,'varchar','150','1','0','1','IEP','IepRefId','0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','ServiceDefinitionCode',4,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Service','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','BeginDate',5,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','EndDate',6,'datetime','10','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','IsRelated',7,'varchar','1','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','IsDirect',8,'varchar','1','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','ExcludesFromGenEd',9,'varchar','1','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','ServiceLocationCode',10,'varchar','150','1','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','ServLoc','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','ServiceProviderTitleCode',11,'varchar','150','1','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','ServProv','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','Sequence',12,'int','2','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','IsESY',13,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','ServiceTime',14,'int','4','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','ServiceFrequencyCode',15,'varchar','150','1','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','ServFreq','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','ServiceProviderSSN',16,'varchar','11','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','StaffEmail',17,'varchar','150','0','0','0',NULL,NULL,'1','SpedStaffMember','StaffEmail',NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Service','ServiceAreaText',18,'varchar','254','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Goal','GoalRefID',1,'varchar','150','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Goal','IepRefID',2,'varchar','150','1','0','1','IEP','IepRefID','0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Goal','Sequence',3,'varchar','2','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Goal','GoalAreaCode',4,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','GoalArea','0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Goal','PSEducation',5,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Goal','PSEmployment',6,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Goal','PSIndependent',7,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Goal','IsEsy',8,'varchar','1','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Goal','UNITOFMEASUREMENT',9,'varchar','100','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Goal','BASELINEDATAPOINT',10,'varchar','100','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Goal','EVALUATIONMETHOD',11,'varchar','100','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Goal','GoalStatement',12,'varchar','8000','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Objective','ObjectiveRefID',1,'varchar','150','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Objective','GoalRefID',2,'varchar','150','1','0','1','Goal','GoalRefID','0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Objective','Sequence',3,'int','2','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','Objective','ObjText',4,'varchar','8000','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','TeamMember','StaffEmail',1,'varchar','150','1','1','1','SpedStaffMember','StaffEmail','0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','TeamMember','StudentRefId',2,'varchar','150','1','1','1','Student','StudentRefID','0',NULL,NULL,NULL,'0',NULL)
INSERT Datavalidation.ValidationRules VALUES  ('Datavalidation','TeamMember','IsCaseManager',3,'varchar','1','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
