IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[EXCENTO].[IEPLRETbl_SC]') AND OBJECTPROPERTY(id, N'IsView') = 1)
DROP VIEW [EXCENTO].[IEPLRETbl_SC]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[EXCENTO].[IEPLRETbl_SC_LOCAL]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [EXCENTO].[IEPLRETbl_SC_LOCAL]
GO

CREATE TABLE [EXCENTO].[IEPLRETbl_SC_LOCAL](
	[IEPLRESeqNum] [bigint] NOT NULL,
	[NotApplicable] [bit] NULL,
	[Itinerant] [bit] NULL,
	[Direct] [bit] NULL,
	[Indirect] [bit] NULL,
	[Resource] [bit] NULL,
	[Consultation] [bit] NULL,
	[Educational] [bit] NULL,
	[Note] [bit] NULL,
	[AssistTech] [bit] NULL,
	[Shadow] [bit] NULL,
	[AppBehavior] [bit] NULL,
	[Other] [bit] NULL,
	[OtherDesc] [ntext] NULL,
	[Classroom] [bit] NULL,
	[InstructAdapt] [bit] NULL,
	[TimeManage] [bit] NULL,
	[AugmentativeComm] [bit] NULL,
	[Braille] [bit] NULL,
	[Auditory] [bit] NULL,
	[CurrAdapt] [bit] NULL,
	[AssistTechDevice] [bit] NULL,
	[OtherAid] [bit] NULL,
	[OtherAidDesc] [nvarchar] NULL,
	[SuppService] [ntext] NULL,
	[SuppAids] [ntext] NULL,
	[OffGradeMod] [ntext] NULL,
	[SpedTimeMeasure] [nvarchar] NULL,
	[RelTimeMeasure] [nvarchar] NULL,
	[SixtyPercent] [int] NULL,
	[OtherSchoolPlace] [int] NULL,
	[PreschoolClass] [int] NULL,
	[HomeBased] [int] NULL,
	[SeparateClass] [int] NULL,
	[ProgramModel] [int] NULL,
	[EdPlacement] [int] NULL,
	[PrePlacement] [int] NULL,
	[CreateID] [nvarchar] NULL,
	[CreateDate] [datetime] NULL,
	[ModifyID] [nvarchar] NULL,
	[ModifyDate] [datetime] NULL,
	[DeleteID] [nvarchar] NULL,
	[Deletedate] [datetime] NULL,
	[Del_Flag] [bit] NOT NULL,
	[itinerantFreq] [real] NULL,
	[DirectFreq] [real] NULL,
	[IndirectFreq] [real] NULL,
	[ResourceFreq] [real] NULL,
	[ConsultationFreq] [real] NULL,
	[EducationalFreq] [real] NULL,
	[NoteFreq] [real] NULL,
	[AssistTechFreq] [real] NULL,
	[ShadowFreq] [real] NULL,
	[AppBehaviorFreq] [real] NULL,
	[OtherFreq] [real] NULL,
	[SpedTime] [real] NULL,
	[RelTime] [real] NULL,
	[Frequency] [nvarchar] NULL,
	[SAEnglish] [bit] NULL,
	[SALanguage] [bit] NULL,
	[SAListen] [bit] NULL,
	[SASpell] [bit] NULL,
	[SARead] [bit] NULL,
	[SAWrite] [bit] NULL,
	[SAStudy] [bit] NULL,
	[SAMath] [bit] NULL,
	[SAScience] [bit] NULL,
	[SASocial] [bit] NULL,
	[SAArt] [bit] NULL,
	[SAForeLang] [bit] NULL,
	[SAHealth] [bit] NULL,
	[SAPhyEdu] [bit] NULL,
	[SAElectives] [bit] NULL,
	[SAElectivesDesc] [ntext] NULL,
	[PreCognitive] [bit] NULL,
	[PreComm] [bit] NULL,
	[PreFineMotor] [bit] NULL,
	[PreGrossMotor] [bit] NULL,
	[PreSelfHelp] [bit] NULL,
	[PreSocial] [bit] NULL,
	[Assemblies] [bit] NULL,
	[HomeRoom] [bit] NULL,
	[Meals] [bit] NULL,
	[Recess] [bit] NULL,
	[ExtraCurr] [bit] NULL,
	[EduPercent] [int] NULL,
	[HomeHosPlace] [int] NULL,
	[StudentAttend] [bit] NULL,
	[SchoolClass] [bit] NULL,
	[RegularClass] [bit] NULL,
	[HarmEffect] [bit] NULL,
	[Integration] [bit] NULL,
	[StudProgress] [ntext] NULL
) ON [PRIMARY]
GO

CREATE VIEW [EXCENTO].[IEPLRETbl_SC]
AS
	SELECT * FROM [EXCENTO].[IEPLRETbl_SC_LOCAL]
GO