INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9409913565421550', N'District File Import                                                                                ', N'DISTRICT                                                                                            ', N'ESTAGE          ', N'c:\vb6code\worldstage\importfiles\district.csv                                                                                                                                                                                                            ', N'4049140057838705', N'4049142003445579', N'4049114733198533', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 2, N'TABLE     ', CAST(2 AS Decimal(3, 0)), NULL, NULL, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9409913580322438', N'School File Import                                                                                  ', N'SCHOOL                                                                                              ', N'ESTAGE          ', N'c:\vb6code\worldstage\importfiles\school.csv                                                                                                                                                                                                              ', N'4049140057838705', N'4049142003445579', N'4049114733198533', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 2, N'TABLE     ', CAST(3 AS Decimal(3, 0)), NULL, NULL, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9409914000324783', N'District File Export                                                                                ', N'DISTRICT                                                                                            ', N'ESTAGE          ', N'c:\_worldstage\fllee\exportfiles\district.csv                                                                                                                                                                                                             ', N'4049140057838705', N'4049142003445579', N'4049114712207705', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 0, N'TABLE     ', CAST(2 AS Decimal(3, 0)), NULL, 1, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9409914001200943', N'School File Export                                                                                  ', N'SCHOOL                                                                                              ', N'ESTAGE          ', N'c:\_worldstage\fllee\exportfiles\school.csv                                                                                                                                                                                                               ', N'4049140057838705', N'4049142003445579', N'4049114712207705', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 0, N'TABLE     ', CAST(3 AS Decimal(3, 0)), NULL, 1, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9409916484452047', N'IEP File Import                                                                                     ', N'IEP                                                                                                 ', N'ESTAGE          ', N'c:\vb6code\worldstage\importfiles\iep.csv                                                                                                                                                                                                                 ', N'4049140057838705', N'4049142003445579', N'4049114733198533', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 2, N'TABLE     ', CAST(5 AS Decimal(3, 0)), NULL, NULL, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9409916493680573', N'Service File Import                                                                                 ', N'SERVICE                                                                                             ', N'ESTAGE          ', N'c:\vb6code\worldstage\importfiles\service.csv                                                                                                                                                                                                             ', N'4049140057838705', N'4049142003445579', N'4049114733198533', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 2, N'TABLE     ', CAST(7 AS Decimal(3, 0)), NULL, NULL, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9409916495930820', N'Objective File Import                                                                               ', N'OBJECTIVE                                                                                           ', N'ESTAGE          ', N'c:\vb6code\worldstage\importfiles\objective.csv                                                                                                                                                                                                           ', N'4049140057838705', N'4049142003445579', N'4049114733198533', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 2, N'TABLE     ', CAST(9 AS Decimal(3, 0)), NULL, NULL, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9410221454275342', N'TeamMember File Import                                                                              ', N'TEAMMEMBER                                                                                          ', N'ESTAGE          ', N'c:\vb6code\worldstage\importfiles\teammember.csv                                                                                                                                                                                                          ', N'4049140057838705', N'4049142003445579', N'4049114733198533', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 2, N'TABLE     ', CAST(10 AS Decimal(3, 0)), NULL, NULL, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9410308073998260', N'Objective File Export                                                                               ', N'OBJECTIVE                                                                                           ', N'ESTAGE          ', N'c:\_worldstage\fllee\exportfiles\objective.csv                                                                                                                                                                                                            ', N'4049140057838705', N'4049142003445579', N'4049114712207705', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 0, N'TABLE     ', CAST(9 AS Decimal(3, 0)), NULL, 1, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9434810500156363', N'Goal File Import                                                                                    ', N'GOAL                                                                                                ', N'ESTAGE          ', N'c:\vb6code\worldstage\importfiles\goal.csv                                                                                                                                                                                                                ', N'4049140057838705', N'4049142003445579', N'4049114733198533', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 2, N'TABLE     ', CAST(8 AS Decimal(3, 0)), NULL, NULL, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9434810533234508', N'Goal File Export                                                                                    ', N'GOAL                                                                                                ', N'ESTAGE          ', N'c:\_worldstage\fllee\ExportFiles\Goal.csv                                                                                                                                                                                                                 ', N'4049140057838705', N'4049142003445579', N'4049114712207705', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 0, N'TABLE     ', CAST(8 AS Decimal(3, 0)), NULL, 1, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9448018335109722', N'Student File Import                                                                                 ', N'STUDENT                                                                                             ', N'ESTAGE          ', N'c:\vb6code\worldstage\importfiles\student.csv                                                                                                                                                                                                             ', N'4049140057838705', N'4049142003445579', N'4049114733198533', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 2, N'TABLE     ', CAST(4 AS Decimal(3, 0)), NULL, NULL, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9448020392202949', N'Student File Export                                                                                 ', N'STUDENT                                                                                             ', N'ESTAGE          ', N'c:\_worldstage\fllee\ExportFiles\Student.csv                                                                                                                                                                                                              ', N'4049140057838705', N'4049142003445579', N'4049114712207705', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 0, N'TABLE     ', CAST(4 AS Decimal(3, 0)), NULL, 1, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9448116361898302', N'SelectLists File Import                                                                             ', N'SELECTLISTS                                                                                         ', N'ESTAGE          ', N'c:\vb6code\worldstage\importfiles\selectlists.csv                                                                                                                                                                                                         ', N'4049140057838705', N'4049142003445579', N'4049114733198533', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 2, N'TABLE     ', CAST(1 AS Decimal(3, 0)), NULL, NULL, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9448116381917708', N'SelectLists File Export                                                                             ', N'SELECTLISTS                                                                                         ', N'ESTAGE          ', N'c:\_worldstage\fllee\ExportFiles\SelectLists.csv                                                                                                                                                                                                          ', N'4049140057838705', N'4049142003445579', N'4049114712207705', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 0, N'TABLE     ', CAST(1 AS Decimal(3, 0)), NULL, 1, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9448122022068518', N'SpedStaffMember File Import                                                                         ', N'SPEDSTAFFMEMBER                                                                                     ', N'ESTAGE          ', N'c:\vb6code\worldstage\importfiles\spedstaffmember.csv                                                                                                                                                                                                     ', N'4049140057838705', N'4049142003445579', N'4049114733198533', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 2, N'TABLE     ', CAST(6 AS Decimal(3, 0)), NULL, NULL, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9448201385310732', N'IEP File Export                                                                                     ', N'IEP                                                                                                 ', N'ESTAGE          ', N'c:\_worldstage\fllee\ExportFiles\IEP.csv                                                                                                                                                                                                                  ', N'4049140057838705', N'4049142003445579', N'4049114712207705', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 0, N'TABLE     ', CAST(5 AS Decimal(3, 0)), NULL, 1, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9448201443111731', N'SpedStaffMember File Export                                                                         ', N'SPEDSTAFFMEMBER                                                                                     ', N'ESTAGE          ', N'c:\_worldstage\fllee\ExportFiles\SpedStaffMember.csv                                                                                                                                                                                                      ', N'4049140057838705', N'4049142003445579', N'4049114712207705', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 0, N'TABLE     ', CAST(6 AS Decimal(3, 0)), NULL, 1, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9448201462643362', N'TeamMember File Export                                                                              ', N'TEAMMEMBER                                                                                          ', N'ESTAGE          ', N'c:\_worldstage\fllee\ExportFiles\TeamMember.csv                                                                                                                                                                                                           ', N'4049140057838705', N'4049142003445579', N'4049114712207705', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 0, N'TABLE     ', CAST(10 AS Decimal(3, 0)), NULL, 1, 0)
INSERT [dbo].[dlinkfile] ([dl_fileid], [dl_desc], [dl_table], [dl_dbc], [dllocation], [dl_type], [dl_delim], [dl_direct], [dl_autoei], [dl_notes], [dl_start], [dl_object], [dl_order], [typeid], [dl_header], [dl_quote]) VALUES (N'9448405000588096', N'Service File Export                                                                                 ', N'SERVICE                                                                                             ', N'ESTAGE          ', N'c:\_worldstage\fllee\ExportFiles\Service.csv                                                                                                                                                                                                              ', N'4049140057838705', N'4049142003445579', N'4049114712207705', 0, N'{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Verdana;}}
\viewkind4\uc1\pard\f0\fs17 
\par }
', 0, N'TABLE     ', CAST(7 AS Decimal(3, 0)), NULL, 1, 0)
