DELETE x_DATAVALIDATION.ValidationRules WHERE TableName IN ('Goal','Objective')
--Goal
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','GoalRefID',1,'varchar','150','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','IepRefID',2,'varchar','150','1','0','1','IEP','IepRefID','0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','Sequence',3,'varchar','2','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','GoalAreaCode',4,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','GoalArea','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','SCInstructional',5,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','SCTransition',6,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','SCRelatedService',7,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','IsEsy',8,'varchar','1','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','UNITOFMEASUREMENT',9,'varchar','100','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','BASELINEDATAPOINT',10,'varchar','100','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','EVALUATIONMETHOD',11,'varchar','100','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','GoalStatement',12,'varchar','8000','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
--Objective
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Objective','ObjectiveRefID',1,'varchar','150','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Objective','GoalRefID',2,'varchar','150','1','0','1','Goal','GoalRefID','0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Objective','Sequence',3,'int','2','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Objective','ObjText',4,'varchar','8000','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)