CREATE TABLE ReportArea
(
	ID UNIQUEIDENTIFIER NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Description TEXT
)

ALTER TABLE dbo.ReportArea ADD CONSTRAINT
PK_ReportArea PRIMARY KEY CLUSTERED
(
	ID
)

CREATE TABLE ReportAreaReport
(
	ReportAreaID UNIQUEIDENTIFIER NOT NULL,
	ReportID UNIQUEIDENTIFIER NOT NULL
)

ALTER TABLE dbo.ReportAreaReport ADD CONSTRAINT
PK_ReportAreaReport PRIMARY KEY CLUSTERED
(
	ReportAreaID, ReportID
)

ALTER TABLE dbo.ReportAreaReport ADD CONSTRAINT
FK_ReportArea#Reports FOREIGN KEY (ReportAreaID) 
REFERENCES dbo.ReportArea (ID) 
	ON UPDATE  NO ACTION 
	ON DELETE  CASCADE

ALTER TABLE dbo.ReportAreaReport ADD CONSTRAINT
FK_Report#ReportAreas FOREIGN KEY (ReportID) 
REFERENCES dbo.Report (ID) 
	ON UPDATE  NO ACTION 
	ON DELETE  CASCADE