DELETE x_DATAVALIDATION.ValidationRules
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','StaffSchool','StaffEmail',1,'varchar','150','1','1','1','SpedStaffMember','StaffEmail','0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','StaffSchool','SchoolCode',2,'varchar','10','1','1','1','School','SchoolCode','0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','SelectLists','Type',1,'varchar','20','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','SelectLists','SubType',2,'varchar','20','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','SelectLists','EnrichID',3,'varchar','150','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','SelectLists','StateCode',4,'varchar','10','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','SelectLists','LegacySpedCode',5,'varchar','150','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','SelectLists','EnrichLabel',6,'varchar','254','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','District','DistrictCode',1,'varchar','10','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','District','DistrictName',2,'varchar','254','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','School','SchoolCode',1,'varchar','10','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','School','SchoolName',2,'varchar','254','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','School','DistrictCode',3,'varchar','10','1','1','1','District','DistrictCode','0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','School','MinutesPerWeek',4,'int','4','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','StudentRefID',1,'varchar','150','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','StudentLocalID',2,'varchar','50','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','StudentStateID',3,'varchar','50','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','Firstname',4,'varchar','50','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','MiddleName',5,'varchar','50','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','LastName',6,'varchar','50','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','Birthdate',7,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','Gender',8,'varchar','150','1','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Gender','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','MedicaidNumber',9,'varchar','50','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','GradeLevelCode',10,'varchar','150','1','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Grade','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','ServiceDistrictCode',11,'varchar','10','1','0','0',NULL,NULL,'1','District','Districtcode',NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','ServiceSchoolCode',12,'varchar','10','1','0','0',NULL,NULL,'1','School','Schoolcode ',NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','HomeDistrictCode',13,'varchar','10','1','0','0',NULL,NULL,'1','District','Districtcode',NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','HomeSchoolCode',14,'varchar','10','1','0','0',NULL,NULL,'1','School','Schoolcode ',NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','IsHispanic',15,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','IsAmericanIndian',16,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','IsAsian',17,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','IsBlackAfricanAmerican',18,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','IsHawaiianPacIslander',19,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','IsWhite',20,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','Disability1Code',21,'varchar','150','1','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','Disability2Code',22,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','Disability3Code',23,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','Disability4Code',24,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','Disability5Code',25,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','Disability6Code',26,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','Disability7Code',27,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','Disability8Code',28,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','Disability9Code',29,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Disab','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','EsyElig',30,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','EsyTBDDate',31,'datetime','10','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','ExitDate',32,'datetime','10','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','ExitCode',33,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Exit','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Student','SpecialEdStatus',34,'char','1','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''A'',''E''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','IepRefID',1,'varchar','150','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','StudentRefID',2,'varchar','150','1','1','1','Student','StudentRefID','0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','IEPMeetDate',3,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','IEPStartDate',4,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','IEPEndDate',5,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','NextReviewDate',6,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','InitialEvaluationDate',7,'datetime','10','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','LatestEvaluationDate',8,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','NextEvaluationDate',9,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','EligibilityDate',10,'datetime','10','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','ConsentForServicesDate',11,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','ConsentForEvaluationDate',12,'datetime','10','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','LREAgeGroup',13,'varchar','3','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','LRECode',14,'varchar','150','1','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','LRE','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','MinutesPerWeek',15,'int','4','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','IEP','ServiceDeliveryStatement',16,'varchar','8000','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','SpedStaffMember','StaffEmail',1,'varchar','150','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','SpedStaffMember','Firstname',2,'varchar','50','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','SpedStaffMember','Lastname',3,'varchar','50','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','SpedStaffMember','EnrichRole',4,'varchar','50','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','ServiceType',1,'varchar','50','1','0','0',NULL,NULL,'1','SelectLists','SubType','Service','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','ServiceRefId',2,'varchar','150','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','IepRefId',3,'varchar','150','1','0','1','IEP','IepRefId','0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','ServiceDefinitionCode',4,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','Service','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','BeginDate',5,'datetime','10','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','EndDate',6,'datetime','10','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','IsRelated',7,'varchar','1','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','IsDirect',8,'varchar','1','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','ExcludesFromGenEd',9,'varchar','1','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','ServiceLocationCode',10,'varchar','150','1','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','ServLoc','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','ServiceProviderTitleCode',11,'varchar','150','1','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','ServProv','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','Sequence',12,'int','2','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','IsESY',13,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','ServiceTime',14,'int','4','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','ServiceFrequencyCode',15,'varchar','150','1','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','ServFreq','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','ServiceProviderSSN',16,'varchar','11','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','StaffEmail',17,'varchar','150','0','0','0',NULL,NULL,'1','SpedStaffMember','StaffEmail',NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Service','ServiceAreaText',18,'varchar','254','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','GoalRefID',1,'varchar','150','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','IepRefID',2,'varchar','150','1','0','1','IEP','IepRefID','0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','Sequence',3,'varchar','2','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','GoalAreaCode',4,'varchar','150','0','0','0',NULL,NULL,'1','SelectLists','Legacyspedcode','GoalArea','0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','PSEducation',5,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','PSEmployment',6,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','PSIndependent',7,'varchar','1','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','IsEsy',8,'varchar','1','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','UNITOFMEASUREMENT',9,'varchar','100','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','BASELINEDATAPOINT',10,'varchar','100','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','EVALUATIONMETHOD',11,'varchar','100','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Goal','GoalStatement',12,'varchar','8000','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Objective','ObjectiveRefID',1,'varchar','150','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Objective','GoalRefID',2,'varchar','150','1','0','1','Goal','GoalRefID','0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Objective','Sequence',3,'int','2','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','Objective','ObjText',4,'varchar','8000','1','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','TeamMember','StaffEmail',1,'varchar','150','1','1','1','SpedStaffMember','StaffEmail','0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','TeamMember','StudentRefId',2,'varchar','150','1','1','1','Student','StudentRefID','0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','TeamMember','IsCaseManager',3,'varchar','1','1','1','0',NULL,NULL,'0',NULL,NULL,NULL,'1',' ''Y'',''N''')
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','AccomMod','IEPRefID',1,'varchar','150','1','1','1','IEP','IEPRefID','0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','AccomMod','AccomStatement',2,'varchar','8000','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','AccomMod','ModStatement',3,'varchar','8000','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','SchoolProgressFrequency','SchoolCode',1,'varchar','10','1','1','1','School','SchoolCode','0',NULL,NULL,NULL,'0',NULL)
INSERT x_DATAVALIDATION.ValidationRules VALUES  ('x_DATAVALIDATION','SchoolProgressFrequency','FrequencyName',2,'varchar','50','0','0','0',NULL,NULL,'0',NULL,NULL,NULL,'0',NULL)
--SELECT * FROM x_DATAVALIDATION.ValidationRules